### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by darcythomas**
Added how to add Raygun and Serilog packages

### CODE REVIEW

**Review by QuantumNightmare — COMMENTED** [review]
The code snippet now kind of looks like it's part of the NuGet explanation. I'd suggest either adding some more text above the code snippet to split it up a little - or pull the NuGet docs up into a different section with a different title.

**Comment by darcythomas** [comment]
> The code snippet now kind of looks like it's part of the NuGet explanation. I'd suggest either adding some more text above the code snippet to split it up a little - or pull the NuGet docs up into a different section with a different title.

Hows that?

**Comment by QuantumNightmare** [comment]
That layout looks better to me, thanks. One other thought I had is that mentioning "command line" and "Program.Main" may be a bit specific. Instead, you could use the VS NuGet package manager, or set up the logger in Global.asax.Application_Start. Perhaps this could be written in a more generic way - let me know what you think about this.

**Review by QuantumNightmare — APPROVED** [review]
Looks good, thanks for the edits

**Pull request merged**
